-- 코드를 입력하세요
-- SUBSTRING(HIRE_YMD, 1, 10)
-- LEFT(HIRE_YMD, 10)
SELECT DR_NAME, DR_ID, MCDP_CD, DATE_FORMAT(HIRE_YMD, "%Y-%m-%d") as HIRE_YMD
FROM DOCTOR
WHERE MCDP_CD="CS" OR MCDP_CD="GS"
ORDER BY HIRE_YMD DESC, DR_NAME ASC